### PR TITLE
Cleaned up ordering of engines etc

### PR DESCRIPTION
**Pull request by NathanKell**
Also removed a few duplicates and misplaced prior stuff (not yours @mcirish3, other folks)

@pjf can you double check the RPWS and DMagic / Universal Storage parts? I know nothing about 'em...

### CODE REVIEW

**Comment by pjf** [comment]
Yo dawg, I heard you liked pull requests... ;)

**Comment by pjf** [comment]
This PR doesn't make any changes to the DMagic Orbital Science or Universal Storage parts that I can see, so all clear with me. :)

**Comment by NathanKell** [comment]
@pjf <3
As to the question, find 'rpws' on the right side [here](https://github.com/KSP-RO/RP-0/pull/137/files)

**Comment by pjf** [comment]
Likewise mcrish3/patch-3 doesn't change them either.

**Comment by pjf** [comment]
>   As to the question, find 'rpws' on the right side here

Oh! My mistake. Checking now.

**Comment by pjf** [comment]
Ah! I've already placed the RPWS in electrics (along with an explanation as to why they're there), so the build system shouldn't build if it spots them twice.

So no, I wouldn't move them to automation (as in KSP-RO/RP-0#137), as this means this rather early technology isn't available until much later in the tech tree.

**Comment by NathanKell** [comment]
@pjf, fixed rpws. What about the two dmagic things from that link? That seems a fine place for them, but you've done much more with DMagic stuff than I.

**Comment by pjf** [comment]
Also, if you want to apply a PR with adjustments on top:

```
git remote add mcirish3 git@github.com:mcirish3/RP-0.git
git checkout -b patching_ur_patch mcrish3/patch-3
# Hack, add, commit, etc.
git checkout master
git merge --no-ff patching_ur_patch
git push
```

**Comment by NathanKell** [comment]
@pjf thanks, I'll do that when done. :)
(Speaking of--yay or nay on the dmagic? I think that's the final bit)

**Pull request merged**
